version: '3'

services:

  jira:
    depends_on:
      - postgresql
    build:
      context: jira/
      dockerfile: Dockerfile
      args:
        - jiraVersion=9.3.0
    networks:
      - jiranet
    volumes:
      - jiraVolume:/var/atlassian/jira
    ports:
      - '8080:8080'
    environment:  
     ATL_JDBC_URL: jdbc:postgresql://database:5432/jiradb
     ATL_JDBC_USER: jira
     ATL_JDBC_PASSWORD: jira
     ATL_DB_DRIVER: org.postgresql.Driver
     ATL_DB_TYPE: postgres72
     JVM_MAXIMUM_MEMORY: 2048m
     JIRA_SHARED_HOME: /var/shared
     CLUSTERED: "false" 
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  postgresql:
    image: postgres:10.22-alpine
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jira'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
  jiraVolume:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge